### Sprint 5 - Modelagem

- Modelo Baseline
- Random Forest
- XGBoost
- Comparação dos Modelos

In [2]:
#Importação de bibliotecas

import pandas as pd

from pathlib import Path

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [3]:
#Importação de datasets processados

ROOT_DIR = Path.cwd().parent

DATA_DIR = ROOT_DIR / "data" / "processed"

X_train = pd.read_csv(DATA_DIR / "X_train.csv")
X_test = pd.read_csv(DATA_DIR / "X_test.csv")

y_train = pd.read_csv(DATA_DIR / "y_train.csv")
y_test = pd.read_csv(DATA_DIR / "y_test.csv")

In [4]:
# Conferir formatos

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(1176, 44)
(294, 44)
(1176, 1)
(294, 1)

In [5]:
# Ajustar formato de y_train e y_test

y_train = y_train.squeeze()
y_test = y_test.squeeze()

#### Modelo Baseline

In [ ]:
# Criar modelo baseline

modelo_lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [7]:
# Treinar modelo

modelo_lr.fit(
    X_train,
    y_train
)

c:\Users\tatsuyasdesire\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
# Fazer previsões usando a base de treino

y_pred_lr = modelo_lr.predict(X_test)

In [9]:
# Métricas de avaliação

accuracy = accuracy_score(
    y_test,
    y_pred_lr
)

precision = precision_score(
    y_test,
    y_pred_lr
)

recall = recall_score(
    y_test,
    y_pred_lr
)

f1 = f1_score(
    y_test,
    y_pred_lr
)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.8605442176870748
Precision: 0.6875
Recall   : 0.23404255319148937
F1 Score : 0.3492063492063492

In [10]:
# Classification report

print(
    classification_report(
        y_test,
        y_pred_lr
    )
)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       247
           1       0.69      0.23      0.35        47

    accuracy                           0.86       294
   macro avg       0.78      0.61      0.64       294
weighted avg       0.84      0.86      0.83       294

In [11]:
# Matriz de confusão

print(
    confusion_matrix(
        y_test,
        y_pred_lr
    )
)

[[242   5]
 [ 36  11]]

##### Conclusão - Modelo Baseline (Regressão Logística)

Foi treinado um modelo de Regressão Logística utilizando os dados preparados na Sprint 4.

O modelo atingiu Accuracy de 86,05%, Precision de 68,75%, Recall de 23,40% e F1 Score de 34,92%.

Apesar da boa Accuracy, observou-se baixa capacidade de identificação dos funcionários que efetivamente deixaram a empresa. O Recall de 23,40% indica que a maioria dos desligamentos não foi detectada pelo modelo.

Esse comportamento é esperado em bases desbalanceadas, nas quais a classe majoritária influencia fortemente o treinamento.

Os resultados obtidos serão utilizados como baseline para comparação com modelos mais robustos nas próximas etapas do projeto.

#### Modelo RandomForest

In [12]:
# Importar biblioteca

from sklearn.ensemble import RandomForestClassifier

In [13]:
# Criação do modelo Random Forest

modelo_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [14]:
# Treinar modelo

modelo_rf.fit(
    X_train,
    y_train
)

RandomForestClassifier(random_state=42)

In [15]:
# Fazer previsões usando a base de treino

y_pred_rf = modelo_rf.predict(
    X_test
)

In [16]:
# Métricas de avaliação

accuracy_rf = accuracy_score(
    y_test,
    y_pred_rf
)

precision_rf = precision_score(
    y_test,
    y_pred_rf
)

recall_rf = recall_score(
    y_test,
    y_pred_rf
)

f1_rf = f1_score(
    y_test,
    y_pred_rf
)

print("Accuracy :", accuracy_rf)
print("Precision:", precision_rf)
print("Recall   :", recall_rf)
print("F1 Score :", f1_rf)

Accuracy : 0.8333333333333334
Precision: 0.4166666666666667
Recall   : 0.10638297872340426
F1 Score : 0.1694915254237288

In [17]:
# Classification report

print(
    classification_report(
        y_test,
        y_pred_rf
    )
)

              precision    recall  f1-score   support

           0       0.85      0.97      0.91       247
           1       0.42      0.11      0.17        47

    accuracy                           0.83       294
   macro avg       0.63      0.54      0.54       294
weighted avg       0.78      0.83      0.79       294

In [18]:
# Matriz de confusão

print(
    confusion_matrix(
        y_test,
        y_pred_rf
    )
)

[[240   7]
 [ 42   5]]

##### Conclusão - Random Forest

O modelo Random Forest foi treinado utilizando os mesmos conjuntos de treino e teste empregados na Regressão Logística.

O modelo apresentou Accuracy de 83,33%, Precision de 41,67%, Recall de 10,64% e F1 Score de 16,95%.

Apesar de obter boa taxa de acerto global, o modelo demonstrou baixa capacidade de identificar funcionários que efetivamente deixaram a empresa, classificando corretamente apenas 5 dos 47 desligamentos observados na base de teste.

Comparado ao modelo baseline de Regressão Logística, o Random Forest apresentou desempenho inferior em todas as métricas relacionadas à identificação da classe de turnover.

#### Modelo XGBoost

In [22]:
# Importar biblioteca

import xgboost
from xgboost import XGBClassifier

In [23]:
# Criar modelo XGBoost

modelo_xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

In [24]:
# Treinar modelo

modelo_xgb.fit(
    X_train,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [25]:
# Fazer previsões usando a base de treino

y_pred_xgb = modelo_xgb.predict(
    X_test
)

In [26]:
# Métricas de avaliação

accuracy_xgb = accuracy_score(
    y_test,
    y_pred_xgb
)

precision_xgb = precision_score(
    y_test,
    y_pred_xgb
)

recall_xgb = recall_score(
    y_test,
    y_pred_xgb
)

f1_xgb = f1_score(
    y_test,
    y_pred_xgb
)

print("Accuracy :", accuracy_xgb)
print("Precision:", precision_xgb)
print("Recall   :", recall_xgb)
print("F1 Score :", f1_xgb)

Accuracy : 0.8605442176870748
Precision: 0.65
Recall   : 0.2765957446808511
F1 Score : 0.3880597014925373

In [27]:
# Classification report

print(
    classification_report(
        y_test,
        y_pred_xgb
    )
)

              precision    recall  f1-score   support

           0       0.88      0.97      0.92       247
           1       0.65      0.28      0.39        47

    accuracy                           0.86       294
   macro avg       0.76      0.62      0.65       294
weighted avg       0.84      0.86      0.84       294

In [28]:
# Matriz de confusão

print(
    confusion_matrix(
        y_test,
        y_pred_xgb
    )
)

[[240   7]
 [ 34  13]]

In [30]:
# RUCAUC

y_prob_xgb = modelo_xgb.predict_proba(X_test)[:, 1]

from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(
    y_test,
    y_prob_xgb
)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.7638039452149195

##### Conclusão - Modelo XGBoost

O modelo XGBoost foi treinado utilizando os conjuntos de treino e teste preparados na Sprint 4.

O modelo apresentou Accuracy de 86,05%, Precision de 65,00%, Recall de 27,66%, F1 Score de 38,81% e ROC-AUC de 76,38%.

Comparado aos modelos anteriores, o XGBoost apresentou o melhor equilíbrio entre identificação de desligamentos e taxa de acerto geral. O modelo foi capaz de identificar 13 dos 47 funcionários que efetivamente deixaram a empresa, superando os resultados obtidos pela Regressão Logística e pelo Random Forest.

O ROC-AUC de 0,764 indica boa capacidade de distinção entre funcionários com risco de desligamento e funcionários com tendência de permanência, tornando o XGBoost o modelo com melhor desempenho até o momento.

In [32]:
# Comparar modelos

comparacao = pd.DataFrame({
    "Modelo": [
        "Regressão Logística",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        0.8605,
        0.8333,
        0.8605
    ],
    "Precision": [
        0.6875,
        0.4167,
        0.6500
    ],
    "Recall": [
        0.2340,
        0.1064,
        0.2766
    ],
    "F1 Score": [
        0.3492,
        0.1695,
        0.3881
    ]
})

comparacao

                Modelo  Accuracy  Precision  Recall  F1 Score
0  Regressão Logística    0.8605     0.6875  0.2340    0.3492
1        Random Forest    0.8333     0.4167  0.1064    0.1695
2              XGBoost    0.8605     0.6500  0.2766    0.3881

In [33]:
# Exportar comparação para Excel

comparacao.to_excel(
    ROOT_DIR / "outputs" / "model_comparison.xlsx",
    index=False
)

#### Conclusão Analítica - Sprint 5

Durante a Sprint 5 foram treinados e avaliados três modelos de Machine Learning para previsão de turnover de funcionários: Regressão Logística, Random Forest e XGBoost.

A Regressão Logística foi utilizada como modelo baseline, apresentando boa Accuracy, porém baixa capacidade de identificação dos desligamentos. O Random Forest apresentou desempenho inferior em praticamente todas as métricas avaliadas.

O modelo XGBoost obteve o melhor equilíbrio entre precisão e capacidade de detecção da classe de turnover, alcançando Accuracy de 86,05%, Recall de 27,66%, F1 Score de 38,81% e ROC-AUC de 76,38%.

Com base nas métricas obtidas, o XGBoost foi selecionado como o melhor modelo do projeto para as etapas seguintes de interpretação e explicabilidade.

#### Sprint Extra - Otimizar precisão XGBoost

In [38]:
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

modelos = {
    
    "XGB Original": XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ),
    
    "XGB Balanceado": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=5
    ),
    
    "XGB Balanceado + Depth 3": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=5,
        max_depth=3
    ),
    
    "XGB Balanceado + 200 Árvores": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=5,
        n_estimators=200
    )
}

resultados = []

for nome, modelo in modelos.items():

    modelo.fit(X_train, y_train)

    y_pred = modelo.predict(X_test)

    y_prob = modelo.predict_proba(X_test)[:,1]

    resultados.append({
        "Modelo": nome,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

comparacao_xgb = pd.DataFrame(resultados)

comparacao_xgb.sort_values(
    by="F1",
    ascending=False
)

,Modelo,Accuracy,Precision,Recall,F1,ROC-AUC
1,XGB Balanceado,0.853741,0.571429,0.340426,0.426667,0.751400
2,XGB Balanceado + Depth 3,0.823129,0.435897,0.361702,0.395349,0.761220
0,XGB Original,0.860544,0.650000,0.276596,0.388060,0.763804
3,XGB Balanceado + 200 Árvores,0.840136,0.500000,0.297872,0.373333,0.753812

In [39]:
# Exportar modelo otimizado

from pathlib import Path
import joblib

MODEL_PATH = Path("../models/xgb_turnover.pkl")

joblib.dump(
    modelo_xgb_otimizado,
    MODEL_PATH
)

['..\\models\\xgb_turnover.pkl']

#### Conclusão Técnica - Sprint Extra

O modelo XGBoost Balanceado apresentou o melhor equilíbrio entre capacidade de detecção dos desligamentos e desempenho geral.

Embora tenha ocorrido uma pequena redução na Accuracy e na Precision em comparação ao modelo original, houve aumento significativo do Recall e do F1 Score.

O Recall aumentou de 27,66% para 34,04%, indicando maior capacidade de identificar funcionários que efetivamente deixaram a empresa.

O F1 Score aumentou de 38,81% para 42,67%, demonstrando melhor equilíbrio entre precisão e sensibilidade.